### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by Suleman-Elahi** [underpig1/octos#2]
https://www.virustotal.com/gui/file/49125f4ca5e4da2b2d3ad266d94e1f99b8ab976647b0db3a91344d6ed27360bb?nocache=1

**Comment by Phoenix1o1** [comment]
Great response to the issue.
Unfortunately, if you don't message all the vendors who flagged it (at least 4 as per VirusTotal) the files keep getting deleted from the running program causing misbehaviour.
Not quite sure that is the best way to release a software

**Comment by underpig1** [comment]
Sorry for closing without a response, but please read the disclaimer under "Installation" in the docs first. As far as I can tell from the analysis it gave me, the virus detection that was posted in this issue only flags it as malware because it makes some IP calls with the software having not been signed and certified yet (again, please read the note). Please understand that at the moment I only wish to get feedback and suggestions before I fully release it for the Microsoft Store, but by that time I will have the code signed and these flags will be resolved. Thank you for your concern.
